def log_progress(sequence, every=None, size=None, name='Items'):
    from ipywidgets import IntProgress, HTML, VBox
    from IPython.display import display

    is_iterator = False
    if size is None:
        try:
            size = len(sequence)
        except TypeError:
            is_iterator = True
    if size is not None:
        if every is None:
            if size <= 200:
                every = 1
            else:
                every = int(size / 200)     # every 0.5%
    else:
        assert every is not None, 'sequence is iterator, set every'

    if is_iterator:
        progress = IntProgress(min=0, max=1, value=1)
        progress.bar_style = 'info'
    else:
        progress = IntProgress(min=0, max=size, value=0)
    label = HTML()
    box = VBox(children=[label, progress])
    display(box)

    index = 0
    try:
        for index, record in enumerate(sequence, 1):
            if index == 1 or index % every == 0:
                if is_iterator:
                    label.value = '{name}: {index} / ?'.format(
                        name=name,
                        index=index
                    )
                else:
                    progress.value = index
                    label.value = u'{name}: {index} / {size}'.format(
                        name=name,
                        index=index,
                        size=size
                    )
            yield record
    except:
        progress.bar_style = 'danger'
        raise
    else:
        progress.bar_style = 'success'
        progress.value = index
        label.value = "{name}: {index}".format(
            name=name,
            index=str(index or '?')
        )

families = ['Agaricus',
'Amanita',
'Apioperdon',
'Auricularia',
'Boletus',
'Calvatia',
'Cantharellus',
'Chroogomphus',
'Clitocybe',
'Cortinarius',
'Craterellus',
'Entoloma',
'Gyromitra',
'Hydnum',
'Imleria',
'Inocybe',
'Kuehneromyces',
'Laccaria',
'Lactarius',
'Leccinum',
'Lepista',
'Lyophyllum',
'Macrolepiota',
'Morchella',
'Mycena',
'Pleurotus',
'Russula',
'Sparassis',
'Suillus',
'Terfezia',
'Tricholoma',
'Tuber',
'Xerocomus']

species_list = ['Agaricus arvensis',
 'Agaricus augustus',
 'Agaricus bisporus',
 'Agaricus bitorquis',
 'Agaricus campestris',
 'Agaricus cupreobrunneus',
 'Agaricus dulcidulus',
 'Agaricus impudicus',
 'Agaricus langei',
 'Agaricus lanipes',
 'Agaricus litoralis',
 'Agaricus moelleri',
 'Agaricus subfloccosus',
 'Agaricus subperonatus',
 'Agaricus sylvaticus',
 'Agaricus sylvicola',
 'Agaricus xanthodermus',
 'Amanita ceciliae',
 'Amanita citrina',
 'Amanita crocea',
 'Amanita excelsa',
 'Amanita franchetii',
 'Amanita fulva',
 'Amanita gemmata',
 'Amanita lividopallescens',
 'Amanita muscaria',
 'Amanita pantherina',
 'Amanita phalloides',
 'Amanita porphyria',
 'Amanita rubescens',
 'Amanita strobiliformis',
 'Amanita submembranacea',
 'Amanita vaginata',
 'Amanita virosa',
 'Auricularia auricula-judae',
 'Auricularia mesenterica',
 'Boletus aereus',
 'Boletus edulis',
 'Boletus pinophilus',
 'Boletus reticulatus',
 'Boletus subtomentosus',
 'Calvatia gigantea',
 'Cantharellus cibarius',
 'Cantharellus cinereus',
 'Cantharellus melanoxeros',
 'Chroogomphus rutilus',
 'Clitocybe agrestis',
 'Clitocybe costata',
 'Clitocybe diatreta',
 'Clitocybe fragrans',
 'Clitocybe gibba',
 'Clitocybe metachroa',
 'Clitocybe nebularis',
 'Clitocybe odora',
 'Clitocybe phaeophthalma',
 'Clitocybe phyllophila',
 'Clitocybe rivulosa',
 'Clitocybe squamulosa',
 'Clitocybe vibecina',
 'Cortinarius acutus',
 'Cortinarius alboviolaceus',
 'Cortinarius anomalus',
 'Cortinarius anserinus',
 'Cortinarius aprinus',
 'Cortinarius armillatus',
 'Cortinarius balteatocumatilis',
 'Cortinarius barbatus',
 'Cortinarius biformis',
 'Cortinarius bolaris',
 'Cortinarius caerulescens',
 'Cortinarius camphoratus',
 'Cortinarius caninus',
 'Cortinarius caperatus',
 'Cortinarius cinnabarinus',
 'Cortinarius citrinus',
 'Cortinarius croceocoeruleus',
 'Cortinarius croceus',
 'Cortinarius decipiens',
 'Cortinarius delibutus',
 'Cortinarius elegantissimus',
 'Cortinarius flexipes',
 'Cortinarius hemitrichus',
 'Cortinarius hinnuleus',
 'Cortinarius humolens',
 'Cortinarius infractus',
 'Cortinarius largus',
 'Cortinarius limonius',
 'Cortinarius livido-ochraceus',
 'Cortinarius malicorius',
 'Cortinarius mucosus',
 'Cortinarius multiformis',
 'Cortinarius obtusus',
 'Cortinarius olivaceofuscus',
 'Cortinarius purpurascens',
 'Cortinarius purpureus',
 'Cortinarius rubellus',
 'Cortinarius sanguineus',
 'Cortinarius saniosus',
 'Cortinarius saturninus',
 'Cortinarius semisanguineus',
 'Cortinarius sphagnophilus',
 'Cortinarius subtortus',
 'Cortinarius talus',
 'Cortinarius torvus',
 'Cortinarius traganus',
 'Cortinarius triumphans',
 'Cortinarius trivialis',
 'Cortinarius turgidus',
 'Cortinarius uliginosus',
 'Cortinarius umbrinolens',
 'Cortinarius vernus',
 'Cortinarius violaceus',
 'Cortinarius vulpinus',
 'Craterellus cornucopioides',
 'Craterellus lutescens',
 'Entoloma araneosum',
 'Entoloma asprellum',
 'Entoloma atrocoeruleum',
 'Entoloma bloxamii',
 'Entoloma cetratum',
 'Entoloma clypeatum',
 'Entoloma conferendum',
 'Entoloma euchroum',
 'Entoloma exile',
 'Entoloma formosum',
 'Entoloma griseocyaneum',
 'Entoloma hebes',
 'Entoloma incanum',
 'Entoloma incarnatofuscescens',
 'Entoloma lividoalbum',
 'Entoloma mougeotii',
 'Entoloma neglectum',
 'Entoloma papillatum',
 'Entoloma pleopodium',
 'Entoloma prunuloides',
 'Entoloma rhodocylix',
 'Entoloma rhodopolium',
 'Entoloma sepium',
 'Entoloma sericatum',
 'Entoloma sericeum',
 'Entoloma serrulatum',
 'Entoloma sordidulum',
 'Entoloma undatum',
 'Entoloma vernum',
 'Gyromitra esculenta',
 'Gyromitra gigas',
 'Gyromitra infula',
 'Hydnum repandum',
 'Hydnum rufescens',
 'Imleria badia',
 'Inocybe appendiculata',
 'Inocybe asterospora',
 'Inocybe cincinnata',
 'Inocybe corydalina',
 'Inocybe curvipes',
 'Inocybe flocculosa',
 'Inocybe fuscidula',
 'Inocybe geophylla',
 'Inocybe griseolilacina',
 'Inocybe lacera',
 'Inocybe lanuginosa',
 'Inocybe mixtilis',
 'Inocybe napipes',
 'Inocybe sindonia',
 'Inocybe whitei',
 'Kuehneromyces mutabilis',
 'Laccaria amethystina',
 'Laccaria bicolor',
 'Laccaria laccata',
 'Laccaria proxima',
 'Laccaria tortilis',
 'Lactarius acerrimus',
 'Lactarius acris',
 'Lactarius albocarneus',
 'Lactarius aspideus',
 'Lactarius aurantiacus',
 'Lactarius azonites',
 'Lactarius blennius',
 'Lactarius camphoratus',
 'Lactarius chrysorrheus',
 'Lactarius circellatus',
 'Lactarius controversus',
 'Lactarius deliciosus',
 'Lactarius deterrimus',
 'Lactarius fluens',
 'Lactarius fulvissimus',
 'Lactarius glyciosmus',
 'Lactarius helvus',
 'Lactarius hepaticus',
 'Lactarius lignyotus',
 'Lactarius lilacinus',
 'Lactarius obscuratus',
 'Lactarius pallidus',
 'Lactarius piperatus',
 'Lactarius porninsis',
 'Lactarius pterosporus',
 'Lactarius pubescens',
 'Lactarius pyrogalus',
 'Lactarius quieticolor',
 'Lactarius quietus',
 'Lactarius romagnesii',
 'Lactarius rubrocinctus',
 'Lactarius rufus',
 'Lactarius ruginosus',
 'Lactarius scoticus',
 'Lactarius serifluus',
 'Lactarius subdulcis',
 'Lactarius tabidus',
 'Lactarius torminosus',
 'Lactarius trivialis',
 'Lactarius vellereus',
 'Lactarius vietus',
 'Lactarius volemus',
 'Leccinum aurantiacum',
 'Leccinum duriusculum',
 'Leccinum scabrum',
 'Leccinum variicolor',
 'Leccinum versipelle',
 'Leccinum vulpinum',
 'Lepista irina',
 'Lepista nuda',
 'Lepista panaeolus',
 'Lepista personata',
 'Lepista sordida',
 'Lyophyllum decastes',
 'Lyophyllum paelochroum',
 'Macrolepiota excoriata',
 'Macrolepiota mastoidea',
 'Macrolepiota procera',
 'Morchella esculenta',
 'Mycena abramsii',
 'Mycena acicula',
 'Mycena aetites',
 'Mycena amicta',
 'Mycena arcangeliana',
 'Mycena aurantiomarginata',
 'Mycena capillaripes',
 'Mycena capillaris',
 'Mycena chlorantha',
 'Mycena cinerella',
 'Mycena citrinomarginata',
 'Mycena clavicularis',
 'Mycena clavularis',
 'Mycena crocata',
 'Mycena diosma',
 'Mycena epipterygia',
 'Mycena erubescens',
 'Mycena filopes',
 'Mycena flavescens',
 'Mycena galericulata',
 'Mycena galopus',
 'Mycena haematopus',
 'Mycena inclinata',
 'Mycena leptocephala',
 'Mycena meliigena',
 'Mycena metata',
 'Mycena olivaceomarginata',
 'Mycena pelianthina',
 'Mycena polygramma',
 'Mycena pseudocorticola',
 'Mycena pterigena',
 'Mycena pura',
 'Mycena purpureofusca',
 'Mycena renati',
 'Mycena rosea',
 'Mycena rosella',
 'Mycena rubromarginata',
 'Mycena sanguinolenta',
 'Mycena silvae-nigrae',
 'Mycena stipata',
 'Mycena stylobates',
 'Mycena vitilis',
 'Mycena vulgaris',
 'Pleurotus dryinus',
 'Pleurotus ostreatus',
 'Pleurotus pulmonarius',
 'Russula acrifolia',
 'Russula adusta',
 'Russula aeruginea',
 'Russula amoenolens',
 'Russula atropurpurea',
 'Russula atrorubens',
 'Russula aurea',
 'Russula aurora',
 'Russula brunneoviolacea',
 'Russula caerulea',
 'Russula cessans',
 'Russula chloroides',
 'Russula claroflava',
 'Russula cuprea',
 'Russula curtipes',
 'Russula cyanoxantha',
 'Russula decolorans',
 'Russula delica',
 'Russula densifolia',
 'Russula emetica',
 'Russula faginea',
 'Russula farinipes',
 'Russula fellea',
 'Russula foetens',
 'Russula fragilis',
 'Russula grata',
 'Russula graveolens',
 'Russula grisea',
 'Russula heterophylla',
 'Russula illota',
 'Russula insignis',
 'Russula integra',
 'Russula ionochlora',
 'Russula laccata',
 'Russula laeta',
 'Russula luteotacta',
 'Russula maculata',
 'Russula melliolens',
 'Russula nauseosa',
 'Russula nitida',
 'Russula nobilis',
 'Russula ochroleuca',
 'Russula odorata',
 'Russula olivacea',
 'Russula paludosa',
 'Russula parazurea',
 'Russula pelargonia',
 'Russula pseudointegra',
 'Russula puellaris',
 'Russula queletii',
 'Russula risigallina',
 'Russula romellii',
 'Russula rosea',
 'Russula sanguinea',
 'Russula sardonia',
 'Russula solaris',
 'Russula velenovskyi',
 'Russula versicolor',
 'Russula vesca',
 'Russula veternosa',
 'Russula violeipes',
 'Russula virescens',
 'Russula viscida',
 'Russula xerampelina',
 'Sparassis crispa',
 'Suillus bovinus',
 'Suillus flavidus',
 'Suillus granulatus',
 'Suillus grevillei',
 'Suillus luteus',
 'Suillus variegatus',
 'Suillus viscidus',
 'Tricholoma aestuans',
 'Tricholoma albobrunneum',
 'Tricholoma arvernense',
 'Tricholoma atrosquamosum',
 'Tricholoma aurantium',
 'Tricholoma cingulatum',
 'Tricholoma columbetta',
 'Tricholoma equestre',
 'Tricholoma focale',
 'Tricholoma fulvum',
 'Tricholoma imbricatum',
 'Tricholoma lascivum',
 'Tricholoma orirubens',
 'Tricholoma pessundatum',
 'Tricholoma populinum',
 'Tricholoma portentosum',
 'Tricholoma psammopus',
 'Tricholoma saponaceum',
 'Tricholoma scalpturatum',
 'Tricholoma sejunctum',
 'Tricholoma stans',
 'Tricholoma stiparophyllum',
 'Tricholoma sulphureum',
 'Tricholoma terreum',
 'Tricholoma ustale',
 'Tricholoma vaccinum',
 'Tuber aestivum',
 'Tuber borchii']


uncleaned_species_list = ['Agaricus arvensis',
 'Agaricus augustus',
 'Agaricus bernardii',
 'Agaricus bisporus',
 'Agaricus bitorquis',
 'Agaricus bohusii',
 'Agaricus brunneolus',
 'Agaricus campestris',
 'Agaricus crocodilinus',
 'Agaricus cupreobrunneus',
 'Agaricus dulcidulus',
 'Agaricus impudicus',
 'Agaricus langei',
 'Agaricus lanipes',
 'Agaricus litoralis',
 'Agaricus moelleri',
 'Agaricus subfloccosus',
 'Agaricus subperonatus',
 'Agaricus sylvaticus',
 'Agaricus sylvicola',
 'Agaricus xanthodermus',
 'Amanita ceciliae',
 'Amanita citrina',
 'Amanita crocea',
 'Amanita excelsa',
 'Amanita franchetii',
 'Amanita fulva',
 'Amanita gemmata',
 'Amanita lividopallescens',
 'Amanita muscaria',
 'Amanita pantherina',
 'Amanita phalloides',
 'Amanita porphyria',
 'Amanita rubescens',
 'Amanita strobiliformis',
 'Amanita submembranacea',
 'Amanita vaginata',
 'Amanita virosa',
 'Boletus aereus',
 'Boletus edulis',
 'Boletus ferrugineus',
 'Boletus pinophilus',
 'Boletus reticulatus',
 'Boletus subtomentosus',
 'Clitocybe agrestis',
 'Clitocybe costata',
 'Clitocybe diatreta',
 'Clitocybe fragrans',
 'Clitocybe gibba',
 'Clitocybe metachroa',
 'Clitocybe nebularis',
 'Clitocybe odora',
 'Clitocybe phaeophthalma',
 'Clitocybe phyllophila',
 'Clitocybe rivulosa',
 'Clitocybe squamulosa',
 'Clitocybe vibecina',
 'Mycena abramsii',
 'Mycena acicula',
 'Mycena aetites',
 'Mycena amicta',
 'Mycena arcangeliana',
 'Mycena aurantiomarginata',
 'Mycena belliae',
 'Mycena capillaripes',
 'Mycena capillaris',
 'Mycena chlorantha',
 'Mycena cinerella',
 'Mycena citrinomarginata',
 'Mycena clavicularis',
 'Mycena clavularis',
 'Mycena crocata',
 'Mycena diosma',
 'Mycena epipterygia',
 'Mycena erubescens',
 'Mycena filopes',
 'Mycena flavescens',
 'Mycena galericulata',
 'Mycena galopus',
 'Mycena haematopus',
 'Mycena inclinata',
 'Mycena juniperina',
 'Mycena leptocephala',
 'Mycena luteovariegata',
 'Mycena megaspora',
 'Mycena meliigena',
 'Mycena metata',
 'Mycena olivaceomarginata',
 'Mycena pelianthina',
 'Mycena polygramma',
 'Mycena pseudocorticola',
 'Mycena pterigena',
 'Mycena pura',
 'Mycena purpureofusca',
 'Mycena renati',
 'Mycena rosea',
 'Mycena rosella',
 'Mycena rubromarginata',
 'Mycena sanguinolenta',
 'Mycena silvae-nigrae',
 'Mycena stipata',
 'Mycena stylobates',
 'Mycena tenerrima',
 'Mycena tintinnabulum',
 'Mycena vitilis',
 'Mycena vulgaris',
 'Russula acrifolia',
 'Russula adusta',
 'Russula aeruginea',
 'Russula amoenolens',
 'Russula atropurpurea',
 'Russula atrorubens',
 'Russula aurea',
 'Russula aurora',
 'Russula betularum',
 'Russula brunneoviolacea',
 'Russula caerulea',
 'Russula cessans',
 'Russula chloroides',
 'Russula claroflava',
 'Russula cuprea',
 'Russula curtipes',
 'Russula cyanoxantha',
 'Russula decolorans',
 'Russula delica',
 'Russula densifolia',
 'Russula depallens',
 'Russula emetica',
 'Russula faginea',
 'Russula farinipes',
 'Russula faustiana',
 'Russula fellea',
 'Russula foetens',
 'Russula fragilis',
 'Russula grata',
 'Russula graveolens',
 'Russula grisea',
 'Russula heterophylla',
 'Russula illota',
 'Russula insignis',
 'Russula integra',
 'Russula ionochlora',
 'Russula laccata',
 'Russula laeta',
 'Russula luteotacta',
 'Russula maculata',
 'Russula melliolens',
 'Russula nauseosa',
 'Russula nitida',
 'Russula nobilis',
 'Russula ochroleuca',
 'Russula odorata',
 'Russula olivacea',
 'Russula paludosa',
 'Russula parazurea',
 'Russula pelargonia',
 'Russula praetervisa',
 'Russula pseudointegra',
 'Russula puellaris',
 'Russula queletii',
 'Russula risigallina',
 'Russula romellii',
 'Russula rosea',
 'Russula roseoaurantia',
 'Russula sanguinea',
 'Russula sardonia',
 'Russula seperina',
 'Russula silvestris',
 'Russula solaris',
 'Russula sororia',
 'Russula subrubens',
 'Russula velenovskyi',
 'Russula versicolor',
 'Russula vesca',
 'Russula veternosa',
 'Russula violeipes',
 'Russula virescens',
 'Russula viscida',
 'Russula xerampelina']
